#!/system/bin/sh
#Script to set correct permissions to /system/etc/init.d

busybox mount -o remount,rw -t auto /system
busybox chmod -R 755 /system/etc/init.d
busybox mount -o remount,ro -t auto /system
